name: controle_financeiro_app
description: Um aplicativo simples de controle financeiro pessoal.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
